baseURL = "https://pinetree.network"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Pinetree"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Pinetree"
  # email does still work but is deprecated.
  # use [params.contact.email] instead.
  #email = "john.doe@example.com"
  #description = "Landing Page"
  bio = "Democratizing climate investment"
  avatar = "img/pine-tree.png"
  favicon = "favicon.png"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/pinetreetoken"
    #instagram = "https://instagram.com/jdoe"
    twitter = "https://twitter.com/pinetreetoken"
    
    # You may use (inline) tables for more versatility
    # This allows sorting and even more icons.
    # Just make sure not to mix key-value pairs, inline tables and tables,
    # although keeping keeping this order is ok.
    # See https://toml.io/en/v1.0.0 for details
    0 = { name = "discord", icon = "discord", style = "fab", link = "https://discord.gg/3ZFkK9vzy9" } # empty links are relative to site root
    #[params.contact.discord] # key names are sorted lexicographically
    #  name = "discord" # may be omitted. defaults to key name
    #  icon = "discord" # may be omitted. defaults to key name
    #  #style = "fas" # may be omitted. default = "fas"
    #  link = "https://local-hiking.club"
    #[params.contact.email]
    #  name = "email" # may be omitted. defaults to key name
    #  icon = "envelope" # may be omitted. defaults to key name
    #  style = "fas" # may be omitted. default = "fas"
    #  link = "mailto:john.doe@example.com"
      